<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
    <RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
    <Version>0.1.1</Version>
    <Product>Penrose</Product>
    <Authors>Zhehao Yang</Authors>
    <Copyright>Copyright (C) 2026 Zhehao Yang</Copyright>
    <RepositoryUrl>https://github.com/zzzyang03/penrose</RepositoryUrl>
  </PropertyGroup>
</Project>
